spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: user-service
  redis:
    host: 192.168.50.171
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
#    json格式时间处理
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://192.168.50.171:3306/meio_dev?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.34.9:8888/eureka/
server:
  port: 8777
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.kando.entity
  configuration:
    map-underscore-to-camel-case: true

#
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #            超时时间--2S
            timeoutInMilliseconds: 4000
          strategy: SEMAPHORE
pagehelper:
  helperDialect: mysql
  reasonable: true